/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.KortexDriver
{
    public class Twist : Message
    {
        public const string RosMessageName = "KortexDriver/Twist";

        public float linear_x { get; set; }
        public float linear_y { get; set; }
        public float linear_z { get; set; }
        public float angular_x { get; set; }
        public float angular_y { get; set; }
        public float angular_z { get; set; }

        public Twist()
        {
            this.linear_x = 0.0f;
            this.linear_y = 0.0f;
            this.linear_z = 0.0f;
            this.angular_x = 0.0f;
            this.angular_y = 0.0f;
            this.angular_z = 0.0f;
        }

        public Twist(float linear_x, float linear_y, float linear_z, float angular_x, float angular_y, float angular_z)
        {
            this.linear_x = linear_x;
            this.linear_y = linear_y;
            this.linear_z = linear_z;
            this.angular_x = angular_x;
            this.angular_y = angular_y;
            this.angular_z = angular_z;
        }
    }
}
