/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class DynamicJointState : Message
    {
        public const string RosMessageName = "control_msgs/DynamicJointState";

        public Header header { get; set; }
        //  List of resource names, e.g. ["arm_joint_1", "arm_joint_2", "gripper_joint"]
        public string[] joint_names { get; set; }
        //  Key-value pairs representing interfaces and their corresponding values for each joint listed in `joint_names`
        public InterfaceValue[] interface_values { get; set; }

        public DynamicJointState()
        {
            this.header = new Header();
            this.joint_names = new string[0];
            this.interface_values = new InterfaceValue[0];
        }

        public DynamicJointState(Header header, string[] joint_names, InterfaceValue[] interface_values)
        {
            this.header = header;
            this.joint_names = joint_names;
            this.interface_values = interface_values;
        }
    }
}
