/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class InterfaceValue : Message
    {
        public const string RosMessageName = "control_msgs/InterfaceValue";

        //  List of resource interface names
        public string[] interface_names { get; set; }
        //  Values corresponding to the list of interfaces in `interface_names`, [1.0, 0.0] for example
        public double[] values { get; set; }

        public InterfaceValue()
        {
            this.interface_names = new string[0];
            this.values = new double[0];
        }

        public InterfaceValue(string[] interface_names, double[] values)
        {
            this.interface_names = interface_names;
            this.values = values;
        }
    }
}
