/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Trajectory;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class JointTrajectoryControllerState : Message
    {
        public const string RosMessageName = "control_msgs/JointTrajectoryControllerState";

        public Header header { get; set; }
        public string[] joint_names { get; set; }
        public JointTrajectoryPoint desired { get; set; }
        public JointTrajectoryPoint actual { get; set; }
        public JointTrajectoryPoint error { get; set; }
        //  Redundant, but useful
        public string[] multi_dof_joint_names { get; set; }
        public MultiDOFJointTrajectoryPoint multi_dof_desired { get; set; }
        public MultiDOFJointTrajectoryPoint multi_dof_actual { get; set; }
        public MultiDOFJointTrajectoryPoint multi_dof_error { get; set; }
        //  Redundant, but useful

        public JointTrajectoryControllerState()
        {
            this.header = new Header();
            this.joint_names = new string[0];
            this.desired = new JointTrajectoryPoint();
            this.actual = new JointTrajectoryPoint();
            this.error = new JointTrajectoryPoint();
            this.multi_dof_joint_names = new string[0];
            this.multi_dof_desired = new MultiDOFJointTrajectoryPoint();
            this.multi_dof_actual = new MultiDOFJointTrajectoryPoint();
            this.multi_dof_error = new MultiDOFJointTrajectoryPoint();
        }

        public JointTrajectoryControllerState(Header header, string[] joint_names, JointTrajectoryPoint desired, JointTrajectoryPoint actual, JointTrajectoryPoint error, string[] multi_dof_joint_names, MultiDOFJointTrajectoryPoint multi_dof_desired, MultiDOFJointTrajectoryPoint multi_dof_actual, MultiDOFJointTrajectoryPoint multi_dof_error)
        {
            this.header = header;
            this.joint_names = joint_names;
            this.desired = desired;
            this.actual = actual;
            this.error = error;
            this.multi_dof_joint_names = multi_dof_joint_names;
            this.multi_dof_desired = multi_dof_desired;
            this.multi_dof_actual = multi_dof_actual;
            this.multi_dof_error = multi_dof_error;
        }
    }
}
